user  nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;



    # ===== ЛОГИ =====
    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log warn;
    
    
    # =====================================================
    # DEFAULT SERVER — ЗАГЛУШКА ДЛЯ ЧУЖИХ ДОМЕНОВ
    # =====================================================


    # --- HTTP ---
    server {
        listen 80 default_server;
        server_name _;
        # return 444;
        return 301 https://kload.ru$request_uri;
    }

    # --- HTTPS ---
    server {
        listen 443 ssl default_server;
        server_name _;

        ssl_certificate     /etc/nginx/ssl/dummy.crt;
        ssl_certificate_key /etc/nginx/ssl/dummy.key;

        # return 444;
        return 301 https://kload.ru$request_uri;
    }

    # =====================================================
    # KLOAD.RU — HTTP (certbot + redirect)
    # =====================================================
    server {
        listen 80;
        server_name kload.ru www.kload.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://kload.ru$request_uri;
        }
    }

    # =====================================================
    # KLOAD.RU — HTTPS (основной сайт)
    # =====================================================
    server {
        listen 443 ssl;
        http2 on;
        server_name kload.ru www.kload.ru;

        ssl_certificate     /etc/letsencrypt/live/kload.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kload.ru/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;


        # ========================
        # FAVICON
        # ========================
        location = /favicon.ico {
            root /usr/share/nginx/html/public;
            access_log off;
            log_not_found off;
            expires 30d;          # опционально — хороший кэш
            add_header Cache-Control "public";
        }

        location = /favicon.svg {   # если используете
            root /usr/share/nginx/html/public;
            access_log off;
            log_not_found off;
            expires 30d;
        }

        # ========================
        # FRONTEND (SPA)
        # ========================
        location / {
            proxy_pass http://frontend:80/;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            try_files $uri $uri/ /index.html;

        }

        # ========================
        # API
        # ========================
        location /api/ {
            proxy_pass http://gateway:8000/;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }
        
    }
}
